### PR TITLE
Gifv, gfycat, and webm support

### PR DESCRIPTION
**Pull request by orderedlist**
This PR adds support to embed gifv, gfycat, and webms in the stream. It also uses a throttled scroll method to play videos in the viewport and pause ones that aren't visible, so it doesn't destroy your CPU.

### CODE REVIEW

**Comment by dhg** [comment]
YESSSSSS. I'm currently traveling, but am going to check this out as soon as I can and get it in. Gifv and Gfycat been killin me that they don't show up. r/gifs just not the same when every other one doesn't render. You're my hero.

**Comment by orderedlist** [comment]
bump

**Comment by dhg** [comment]
f*ck it, blind merge. Hope this works <3

**Comment by dhg** [comment]
Oh, just realized some giphy stuff bleed beyond it's container...will get in and try to fix right now.

**Comment by orderedlist** [comment]
Also just realized I'll need to turn off auto play for iOS.

**Pull request merged**
